
### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/market_simulator?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Paris
spring.datasource.username=root
spring.datasource.password=

# spring.datasource.url=jdbc:mysql://164.132.228.232:3306/E-Learnig?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC
# spring.datasource.username=root
# spring.datasource.password=0FAxr7T8anx42++

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080
#server.servlet.context-path=/elearning

spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
## http://localhost:8090/Pocker/swagger-ui/index.html
# Configuration de l'envoi d'e-mails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pokerplanning0@gmail.com
spring.mail.password=tplbpksoyafffair
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
jwt.secret=your-secret-key



logging.level.org.springframework.security=DEBUG

# JWT Configuration
bezkoder.app.jwtSecret= ======================BezKoder=Spring===========================
bezkoder.app.jwtExpirationMs=86400000


##firas
#L'initialisation de api
api.token=ATATT3xFfGF0vteHsiPil5Kwa09pq0_hzi_J8FMVts1Oi-t7pGFUfp7J0St-oByhMOB8WY6Skhiq63ul128ob8IPLq8q0eXlTofC8EezrtEMyEiQGDOC35SatoGbviTLpd6d-R-7liSVvIdmTKqk_EGUOPiOZ34ga4oGKliHCZb4eHrk7lqI9YE=923882AE
#L'initialisation de username
nom.de.utlisateur=firas.dhahri@esprit.tn
#Domain
domain.name=firasdhahri


# Enable Atlassian Connect for Cloud
atlassian.connect.allow-cloud=true

# Enable Atlassian Connect for development mode
atlassian.connect.allow-development=true

# Enable remote installation of your add-on
atlassian.connect.allow-remote-install=true
spring.servlet.multipart.enabled=true


spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB